# Generated by Django 3.0.5 on 2020-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0003_package_statuses_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStatuses',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev_id', models.CharField(max_length=200)),
                ('pck', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=15)),
                ('long', models.BigIntegerField()),
            ],
        ),
    ]
