# Generated by Django 3.0.5 on 2020-04-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0004_gueststatuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sts',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
